site_name: Notes
nav:
  - Architecture:
    - Network: network.md
    - Key Management: keys.md
  - Guides:
    - Ansible: ansible.md
    - Bring Up: bring_up.md
  - Tools:
    - RAID: raid.md
    - Borg: borg.md
    - RClone: rclone.md
    - KVM: kvm.md
  - Services:
    - PiHole: pihole.md
theme: readthedocs
